//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLChecker2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string username { get; set; }
        public int userId { get; set; }
        public string accountType { get; set; }
        public string password { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Student Student { get; set; }
    }
}
