//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLChecker2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int assignmentId { get; set; }
        public int year { get; set; }
        public string semester { get; set; }
        public string databaseName { get; set; }
        public int Staff_staffId { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
