//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLChecker2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deduction
    {
        public int deductionTypeID { get; set; }
        public string deductionType { get; set; }
        public string defaultFeedbackText { get; set; }
    }
}
