//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLChecker2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        public int queryId { get; set; }
        public string questionText { get; set; }
        public string sqlQuery { get; set; }
        public string comment { get; set; }
    }
}
